apiVersion: apps/v1
kind: Deployment
metadata:
  name: newinbtp
  labels:
    app: newinbtp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newinbtp
  template:
    metadata:
      labels:
        app: newinbtp
    spec:
      containers:
        - image: dktrkranz/newinbtp
          imagePullPolicy: Always
          name: newinbtp
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: newinbtp
  labels:
    app: newinbtp
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: newinbtp
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: newinbtp
  labels:
    app: newinbtp
spec:
  service:
    host: newinbtp.ddfb75c.kyma.shoot.live.k8s-hana.ondemand.com
    name: newinbtp
    port: 8080
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
      - GET
      accessStrategies:
        - handler: allow