apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  name: kyma
  namespace: apps
spec:
  url: https://github.com/dktrkranz/kyma.git
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: newinbtp
  namespace: apps
spec:
  runtime: python38
  buildResources:
    limits:
      cpu: 1100m
      memory: 1100Mi
    requests:
      cpu: 700m
      memory: 700Mi
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  minReplicas: 3
  maxReplicas: 5
  source: kyma
  type: git
  reference: master
  baseDir: NewInBTP
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: newinbtp
  namespace: apps
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    path: /.*
  service:
    host: newinbtp.ddfb75c.kyma.shoot.live.k8s-hana.ondemand.com
    name: newinbtp
    port: 80
