apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  name: kyma
  namespace: apps
spec:
  url: https://github.com/dktrkranz/kyma.git
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: idconverter
  namespace: apps
spec:
  runtime: python39
  buildResources:
    limits:
      cpu: 1100m
      memory: 1100Mi
    requests:
      cpu: 700m
      memory: 700Mi
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  minReplicas: 1
  maxReplicas: 1
  source: kyma
  type: git
  reference: main
  baseDir: IDConverter
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: idconverter
  namespace: apps
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    path: /.*
  service:
    host: idconverter.c-063d85c.kyma.ondemand.com
    name: idconverter
    port: 80
